spring:
  profiles:
    active: dev # 로컬 실행 시 기본값
  application:
    name: boogle
  config:
    import: "optional:classpath:secret-${spring.profiles.active}.properties"

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 1209600000

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  logout-redirect-uri: ${KAKAO_LOGOUT_REDIRECT_URI}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: ${NAVER_REDIRECT_URI}