spring:
  application:
    name: demo

  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: boogle-super-secret-key-that-is-over-32-characters-long
  access-token-expiration: 900000
  refresh-token-expiration: 1209600000

kakao:
  client-id: b6638b255ebf5d503bd755eb7d27aac3
  redirect-uri: http://localhost:8080/api/oauth/kakao/callback

naver:
  client-id: Hp3wT4d6Ecem36NtFuCc
  client-secret: V9ET9CHCQv
  redirect-uri: http://localhost:8080/api/oauth/naver/callback