JWT_SECRET=boogle-super-secret-key-that-is-over-32-characters-long

KAKAO_CLIENT_ID=b6638b255ebf5d503bd755eb7d27aac3
KAKAO_CLIENT_SECRET=AOqUkvPIFczhRsfWcOQ2KDnpHPNYS2D5
KAKAO_REDIRECT_URI=http://localhost:8080/api/oauth/kakao/callback
KAKAO_LOGOUT_REDIRECT_URI=http://localhost:8080/api/oauth/kakao/logout/callback

NAVER_CLIENT_ID=Hp3wT4d6Ecem36NtFuCc
NAVER_CLIENT_SECRET=V9ET9CHCQv
NAVER_REDIRECT_URI=http://localhost:8080/api/oauth/naver/callback