jwt.secret=boogle-super-secret-key-that-is-over-32-characters-long

kakao.client-id=b6638b255ebf5d503bd755eb7d27aac3
kakao.client-secret=AOqUkvPIFczhRsfWcOQ2KDnpHPNYS2D5
kakao.redirect-uri=https://www.api.moonsunpower.com/boogle/api/oauth/kakao/callback
kakao.logout-redirect-uri=https://www.api.moonsunpower.com/boogle/api/oauth/kakao/logout/callback

naver.client-id=Hp3wT4d6Ecem36NtFuCc
naver.client-secret=V9ET9CHCQv
naver.redirect-uri=https://www.api.moonsunpower.com/boogle/api/oauth/naver/callback