JWT_SECRET = shivalshivalshivalshival

NAVER_CLIENT_ID = Hp3wT4d6Ecem36NtFuCc
NAVER_CLIENT_SECRET = V9ET9CHCQv
NAVER_REDIRECT_URI = http://localhost:8080/api/oauth/naver/callback

KAKAO_CLIENT_ID = b6638b255ebf5d503bd755eb7d27aac3
KAKAO_REDIRECT_URI = http://localhost:8080/api/oauth/kakao/callback