apiVersion: apps/v1
kind: Deployment
metadata:
  name: boogle-deployment
  labels:
    app: boogle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boogle
  template:
    metadata:
      labels:
        app: boogle
    spec:
      containers:
        - name: boogle
          image: your-docker-registry/boogle:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: boogle-service
spec:
  type: ClusterIP
  selector:
    app: boogle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080